### ISSUE TITLE
Path separators replacement

### ISSUE THREAD

**Issue by lAIRl** [DigitalHolography/Holovibes#105]
Path separator should not be hard-coded as such:

https://github.com/DigitalHolography/Holovibes/blob/340759b4e4f1d3c58866ef4cabb89e13bd019d9a/Holovibes/sources/gui/windows/MainWindow.cc#L2574

It could be a problem in case of the OS differs from Windows (cannot differs at the moment I wrote the issue).

**Comment by NyalephTheCat** [comment]
This was changed recently
