### ISSUE TITLE
ProcessHoloFile Enhancement

### ISSUE THREAD

**Issue by NoeTopeza** [DigitalHolography/Holovibes#474]
ProcessHoloFile Enhancement to add:

- [x]  Recursive folder processing (it should explore sub folder to process the files inside those as well)
- [x]  Multi compute_settings.json support: it should be possible to insert multiple compute settings to have every holo file rendered for each of the compute_settings. (output file name suffix to discuss)
- [x] Last folder path used for input file / compute settings / holovibes executable kept in memory ?
- [x] #489 
- [x] #488

**Comment by NoeTopeza** [comment]
- Last folder path used for input file / compute settings / holovibes executable kept in memory ?

**Comment by noTban** [comment]
- [ ] #489

**Comment by alexispinson** [comment]
This issue is in two differents PR : one for the last one and one for the others.
