### ISSUE TITLE
App should change input buffer size auto depending on situation

### ISSUE THREAD

**Issue by noTban** [DigitalHolography/Holovibes#478]
Sometime the input buffer size isn't big enough when opening a file, causing the app to crash immediately after showing the following message.
![image](https://github.com/user-attachments/assets/dfd6abff-617d-4eb9-9370-b3cbf9130a77)
The crash case should be averted, and maybe auto trying again with smaller buffer size could be a confortable feature.

**Comment by noTban** [comment]
A enqueter dans la fonction `inline void gpuAssertRelease(cudaError_t code)` du fichier `common.cuh`

**Comment by ArthurCourselle** [comment]
Maybe set the record buffer size to the max that cuda can give in set_record_buffer_size if the size is too large. Need to check if possible.

**Comment by ArthurCourselle** [comment]
Issue solved, need to add a warn in the lightui to inform the user that the size is reduced when too large

**Comment by ArthurCourselle** [comment]
Warning added. Issue closed
