### ISSUE TITLE
Crash when importing a file just after importing another

### ISSUE THREAD

**Issue by ArthurCourselle** [DigitalHolography/Holovibes#481]
The  issue happen when we import a file, start the computations, then stop it, then import a new file. This new file can't be imported and the software crash instantly.

**Comment by ArthurCourselle** [comment]
Bug seems to happen only when the second file have a footer.

**Comment by ArthurCourselle** [comment]
Commit 513e8cced9d257f56de33c535887368fbd645445 created the bug

**Comment by Baschtien** [comment]
Issue is fixed
