### ISSUE TITLE
Add ProcessHoloFiles.ps1 to Program Files 

### ISSUE THREAD

**Issue by noTban** [DigitalHolography/Holovibes#488]
When installing Holovibes, [ProcessHoloFiles.ps1](https://github.com/DigitalHolography/Holovibes/releases/download/v13.3.2/ProcessHoloFiles.ps1) should go in Programfiles/Holovibes or Programfiles/ProcessHoloFiles. A link on the Destkop could also be created

**Comment by Baschtien** [comment]
What seems possible (and pretty easy) is to add the .ps1 to the root of the Holovibes folder, created in 'Program Files/{version}/'.
I (for now) have not found another way.

Moreover, launching a .ps1 doesn't seem to be possible by double clicking it, but only by right-click -> run with power shell.
A workaround for that would be to create a .bat file that launches it, or just leave it as it is.

**Comment by Baschtien** [comment]
It is possible to split Holovibes and ProcessHoloFiles ; however there are problems with the uninstaller.

**Comment by simon-riou** [comment]
- Put .ps1 in VERSION/scripts
- Replace .ps1 desktop shortcut by Holovibes desktop shortcut
- Associate the Holovibes.exe used by the .ps1 to the one in the same folder (the same version) -> remove having to choose the Holovibes.exe in the .ps1
- Wrap .ps1 in a .exe or .bat (or other) and maybe create a shortcut somewhere (Documents/Holovibes ?) -> put that also in VERSION/scripts
