### ISSUE TITLE
Change frame descriptor depth to a enum

### ISSUE THREAD

**Issue by Hpn4** [DigitalHolography/Holovibes#531]
The depth of the frame descriptor is used to tell the type of the data (it's the number of 8bits for one pixel):
- `depth = 1`: 8bits
- `depth = 2`: 16bits
- `depth = 4`: 32bits
- `depth = 8`: 64bits: complex number

It will be easier if it's an enum. Like:
```cpp
enum class PixelDepth
{
    Bits8 = 1,
    Bits16 = 2,
    Bits32 = 4,
    Complex = 8
};
```

**Comment by simon-riou** [comment]
Somewhere there's a depth = 6 too.

Seems to be used with the Composite image type, maybe color info ?
