### ISSUE TITLE
Create a base class for all phantom camera and merge the EHoloGrabber

### ISSUE THREAD

**Issue by Hpn4** [DigitalHolography/Holovibes#564]
The `CameraPhantom` class is defined in 4 files, the inerface is exactly the same. Also the `EHoloSubGrabber` is present and the same for the 4 phantom camera.

A way to do it will be to have a base class for `CameraPhantom` and `EHoloGrabber` and then specialize it for each camera.

**Comment by Baschtien** [comment]
Maybe use this opportunity to move code from the headers to the actual code files ¯\_(ツ)_/¯
