### ISSUE TITLE
Useless calls of functions

### ISSUE THREAD

**Issue by ArthurCourselle** [DigitalHolography/Holovibes#588]
/**
     * @brief Apply the updates of the settings on pipe refresh,
     */
    inline void pipe_refresh_apply_updates()
    {
        fourier_transforms_->pipe_refresh_apply_updates();
        image_accumulation_->pipe_refresh_apply_updates();
        pipe_refresh_settings_.apply_updates();
    }

In this function: pipe_refresh_settings_.apply_updates(); is called 3 times in a row, I think we could remove the 2 first lines.

**Comment by Hpn4** [comment]
Each of these three classes have a `pipe_refresh_settings_` variable. Its not the same
