### ISSUE TITLE
Output fps depends on batch size when starting with holo

### ISSUE THREAD

**Issue by simon-riou** [DigitalHolography/Holovibes#591]
It seems that when starting with a batch size of "x", it aligns itself with input fps, but whenever you lower the batch size it increases output fps, or when you higher it it decreases the output fps.

It could sound like an expected behavior, but for example when starting with a batch size of 256 and input fps of 10000 we get currently approximately 9000 output fps, but when you lower the batch size to 32 it increases output fps to 72000 !
OR
When you start with a batch size of 32 and input fps of 10000 we get currently approximately 9000 output fps, but when you increase the batch size to 128 it decreases output fps to 700 !

So, there could be different reason : 

- The compute of the printed output fps is not correct
- The batch size printed on the gui is not accurate with what is inside the settings
- Another deep secret inside the code ... (the worst case)

**Comment by Baschtien** [comment]
Doses that happen in raw mode or processed mode ? Both ?

If in raw mode, it could be Linked to the computations still being done even in raw mode ? (Is that wanted ? Is that even what happens ?)

**Comment by simon-riou** [comment]
Sorry, yes it's happening in RAW mode

**Comment by MaxBA1602** [comment]
Seems Fixed [Link to Commit](https://github.com/DigitalHolography/Holovibes/commit/020e99cc873d12b352f2493d05726e74ca81e419)
