### ISSUE TITLE
Image stabilization

### ISSUE THREAD

**Issue by ArthurCourselle** [DigitalHolography/Holovibes#606]
Implement image stabilization as in mathlab
Need to add a kernel cuda for cross-correlation

**Comment by ArthurCourselle** [comment]
Here is a roadmap:

- [ ] Add the option in the front end and integrate it like fftshift option
- [ ] Add a mask of 0 with a circle of 1 in the middle to keep only the middle of the eye
- [ ] Substract the mean of the image to each pixels (maybe also divide the std in the future in order to nomalize)
- [ ] Apply the cross-correlation between the ref image (first image for now) and each image (check for cuda func) (conv2 ?)
- [ ] Take the argmax of the result of the xcorr, representing the point to stabilize
- [ ] Shift images to the point

**Comment by ArthurCourselle** [comment]
- [ ] Create a StabilizationEnv storing all the buffers
- [ ] Setting up a sliding window (circular queue ?) for the reference image to have stabilization in realtime based on last images.

**Comment by Hpn4** [comment]
./dev.py build && ./build/bin/Holovibes.exe -i "E:\DataHolovibesEPITA2023-2024\test for ps1\241023_BAP0199_OD.holo" -o "E:\DataHolovibesEPITA2023-2024\test for ps1\241023_BAP0199_OD_out.avi" --frame_skip 16 -c "C:\Users\Kurskuser\Documents\Holovibes\Preset\doppler_8b_384_27.json"
