### ISSUE TITLE
Enabling reticle displays full white screen

### ISSUE THREAD

**Issue by TitouanGragnic** [DigitalHolography/Holovibes#621]
Enabling the reticle without having changed at least once the image type will show the reticle on a full white screen.
Oddly, this does not happen if you have changed image type once.

**Comment by TitouanGragnic** [comment]
It seems to be linked to the auto contrast breaking when enabling reticle

**Comment by GustaveHerve** [comment]
have a look at compute_percentile_xy_view i can make it work but i don't know what it really does

**Comment by GustaveHerve** [comment]
The problem comes from here
https://github.com/DigitalHolography/Holovibes/blob/e5102d1407f7046795a11a1dad222eea852750bf/Holovibes/cuda_sources/percentile.cu#L101-L108

When commenting the if (compute_on_sub_zone) part and keeping only the else expression for testing purpose the bug does not occur
