### ISSUE TITLE
Create new repositories for: tools, backend

### ISSUE THREAD

**Issue by Baschtien** [DigitalHolography/Holovibes#684]
Currently, various tools, scripts and other utils have been developped to aid Holovibes development. However, their versioning and availability is hardly monitored.

Creating a new GitHub repository to store them would solve most problems. It would include notably:
- Holo file inspector
- Benchmark viewer

**Comment by Baschtien** [comment]
This can only be done with the DigitalHolography GitHub account (or maybe another admin-level account); see with Michael for how to do this

**Comment by Hpn4** [comment]
Also create a repo that will holds the backend of Holovibes
