### ISSUE TITLE
Add a new settings CameraFps

### ISSUE THREAD

**Issue by GustaveHerve** [DigitalHolography/Holovibes#685]
Add a setting CameraFps which would represent the fps that was set when recording the file. In fact, this setting is the InputFps while recording using a camera.

This fps must not be calculated from the .ini of the camera but from the real fps we have at the input.
This settings must be pass from footers to footers, so that while using .ps1, we keep the same CameraFps. (It will be helpfull to set by default the value of CameraFps to InputFps if there is no value in the footer)

This settings will not be usefull right now in Holovibes but it is in Matlab.
The setting must not be in the compute settings .json files but only in the footer. (that can be discuss with michael)
Ask Alexis for more info.

**Comment by Hpn4** [comment]
This settings is useful in the `fft_freqs` function in `ICompute`. Replace the `setting<settings::InputFPS>()` by the new setting. This function is used in order to calculate moments.

**Comment by Baschtien** [comment]
Done
