### ISSUE TITLE
Wait for API result to accept a GUI change

### ISSUE THREAD

**Issue by noTban** [DigitalHolography/Holovibes#696]
Some settings need some checks before their update is accepted. Those checks were formerly performed in the frontend, and now have been moved in the API. The problem is that the frontend doesn't wait for the process of the API ; a refresh of the frontend is triggered (MainWindow notify) anyway.

In order for the API to be completly independant, and implemented as a library, the functions processing a setting's update must indicate to the frontend if the update was accepted or not.

In case of a modification rejected, a warning log should be sent.

**Comment by Baschtien** [comment]
The same objective as #654, maybe turn this issue as another checkbox in that issue instead ?

**Comment by Hpn4** [comment]
I thought it will be nice to add an error code enum for all API calls (like INVALID_BOUND, COMPUTE_NOT_STARTED, ...) instead of warning log. But i can set up both since logs are more precise
